### ISSUE TITLE
Placeholder text in Withdraw Cash needs to be changed

### ISSUE THREAD

**Issue by BuffsOverNexus** [kylemcshea/homestead-vorp#14]
Change the "insertamount" to something like "amount" or "cash".

![Image](https://user-images.githubusercontent.com/69656765/235514930-f6df7955-585b-44e3-a2a2-3dc5ec4bed89.png)

**Comment by kylemcshea** [comment]
good to close



![Image](https://user-images.githubusercontent.com/46171436/235762867-e6d83cbe-9120-4495-a63e-4571310d243a.png)
