### ISSUE TITLE
either replace or get rid of delivery job

### ISSUE THREAD

**Issue by kylemcshea** [kylemcshea/homestead-vorp#27]

**Comment by kylemcshea** [comment]
@megasmidge can you find out what script is handling the deliveries? This will help us with knowing what to remove.

**Comment by megasmidge** [comment]
This is VORP_postman
confirmed

**Comment by kylemcshea** [comment]
Then yeah we should remove it in a PR. Can I assign this task to you? @megasmidge

**Comment by kylemcshea** [comment]
Optimize vorp_postman is tied to this. We just deleted and thats how we resolved :)
