### ISSUE TITLE
When I create a character without a space in the "name" field, it will not work

### ISSUE THREAD

**Issue by BuffsOverNexus** [kylemcshea/homestead-vorp#6]

**Comment by BuffsOverNexus** [comment]
![issue](https://user-images.githubusercontent.com/69656765/235395204-c4755f21-6b87-4a09-be87-a2163bec5034.png)

**Comment by kylemcshea** [comment]
we split up the character naming by making it where first name has its own input and last name has its own input so this issue is no longer in our server.
